export interface GameRule {
  id: string;
  title: string;
  emoji: string;
  color: string;
  tagline: string;
  goal: string;
  rules: string[];
  proTip: string;
}

export const GAME_RULES: Record<string, GameRule> = {
  bingo: {
    id: "bingo",
    title: "BeachBingo",
    emoji: "🎱",
    color: "#0ea5e9",
    tagline: "Das Spiel, bei dem Schreien zur Pflicht gehört.",
    goal: "Als Erstes eine vollständige Reihe markieren — und BINGO brüllen!",
    rules: [
      "Jeder Spieler erhält eine zufällige Bingo-Karte mit Zahlen.",
      "Der Host zieht Zahl für Zahl — tippe drauf, wenn du sie auf deiner Karte hast.",
      "Vollständige Reihe (horizontal, vertikal oder diagonal) = BINGO!",
      "2–6 Spieler können gleichzeitig mitspielen.",
    ],
    proTip: "Schreie \"BINGO!\" so laut wie möglich — auch wenn du noch nicht gewonnen hast. Schockiert die Konkurrenz und macht gute Stimmung.",
  },
  pong: {
    id: "pong",
    title: "BeachVolley",
    emoji: "🏓",
    color: "#f97316",
    tagline: "Sand, Schweiß und Spielverderber.",
    goal: "Den Ball übers Netz spielen und mehr Punkte als der Gegner holen.",
    rules: [
      "Tippe auf deine Seite, um den Ball zurückzuschlagen.",
      "Wer den Ball nicht rechtzeitig zurückspielt, verliert den Punkt.",
      "Erster mit der festgelegten Punktzahl gewinnt den Satz.",
      "Mehrere Runden und Sätze möglich.",
    ],
    proTip: "Ballgefühl ist alles. Handy-Schweiß ist dein Feind. Hände vor dem Spiel abwischen — dringend empfohlen.",
  },
  vier: {
    id: "vier",
    title: "Vier4Bier",
    emoji: "🍺",
    color: "#f59e0b",
    tagline: "Strategie meets Strandbar. Denken optional.",
    goal: "Vier eigene Steine in einer Reihe — und den Gegner zum Trinken bringen.",
    rules: [
      "Spieler setzen abwechselnd einen Stein in eine der 7 Spalten.",
      "Steine fallen nach unten (Schwerkraft gilt auch am Strand).",
      "Vier Steine in einer Reihe — horizontal, vertikal oder diagonal — gewinnt.",
      "Verlierer trinkt. Bei Unentschieden trinken alle. So einfach ist das.",
      "Auch gegen KI spielbar — die trinkt leider nicht mit.",
    ],
    proTip: "Strategie ist gut. Den Gegner ablenken ist besser. Auf die Möwen zeigen wirkt eigentlich immer.",
  },
  pirates: {
    id: "pirates",
    title: "BeachPirates",
    emoji: "🐙",
    color: "#a855f7",
    tagline: "Kein echter Rum. Trotzdem viel Action.",
    goal: "So viele Wellen von Quallen, Muscheln und Fischen abwehren wie möglich.",
    rules: [
      "Bewege deine Figur mit Wischgesten oder dem Steuerkreuz.",
      "Dein Charakter schießt automatisch auf ankommende Gegner.",
      "Jeder Treffer kostet dich ein Leben.",
      "Besiege ganze Wellen für Bonuspunkte.",
      "Sammle Power-Ups für temporäre Vorteile.",
    ],
    proTip: "Quallen mögen keine Strandläufer. Du magst keine Quallen. Ihr habt mehr gemeinsam als gedacht — und trotzdem müssen sie weg.",
  },
  worm: {
    id: "worm",
    title: "Wattwurm",
    emoji: "🪱",
    color: "#22c55e",
    tagline: "Snake. Aber nass.",
    goal: "So lang wie möglich überleben, ohne den Rand oder dich selbst zu treffen.",
    rules: [
      "Steuere den Wurm mit Wischgesten oder Richtungstasten.",
      "Friss Krabben, Muscheln und Fische für Punkte und Länge.",
      "Rand berühren oder in den eigenen Körper fahren = Game Over.",
      "Je länger du überlebst, desto schneller wird der Wurm.",
    ],
    proTip: "Würmer haben keine Bremsen. Du auch nicht. Hoffentlich hast du gute Reflexe — und kein zweites Bier in der Hand.",
  },
  strandturm: {
    id: "strandturm",
    title: "Strandturm",
    emoji: "🗼",
    color: "#dc2626",
    tagline: "Was raufgeht, kommt auch runter. Besonders Kokosnüsse.",
    goal: "Klettere den Pier so hoch wie möglich — und weiche Kokosnüssen aus.",
    rules: [
      "Tippe links oder rechts, um die Seite zu wechseln.",
      "Kokosnüsse fallen von oben — weiche ihnen aus.",
      "Je höher du kletterst, desto mehr Punkte bekommst du.",
      "Ein Treffer = Game Over. Kein zweites Leben, kein Pardon.",
    ],
    proTip: "Physik ist auf dem Pier leider keine Meinung. Die Kokosnüsse sind sehr real. Dein Kopf auch.",
  },
  brandung: {
    id: "brandung",
    title: "Brandung",
    emoji: "🌊",
    color: "#0d9488",
    tagline: "31 ist die magische Zahl. Manchmal das Beste, worauf man hoffen kann.",
    goal: "Als Erstes Karten mit einem Gesamtwert nahe 31 in einer einzigen Farbe halten.",
    rules: [
      "Jeder startet mit 3 Karten auf der Hand.",
      "Reihum: eine Karte vom Stapel nehmen, eine ablegen.",
      "Kartenwerte: Ass = 11, Bildkarten = 10, alle anderen = Nennwert.",
      "Nur Karten gleicher Farbe zählen zusammen!",
      "Wer \"Klopfen\" sagt, gibt allen anderen eine letzte Runde.",
      "Wer am Ende den niedrigsten Wert hat, verliert ein Leben.",
      "Alle 3 Leben verloren = ausgeschieden. Letzter mit Leben gewinnt!",
    ],
    proTip: "\"Klopfen\" zu früh ist wie zu früh \"BINGO\" zu rufen. Klappt manchmal. Meistens endet es in kollektivem Augenrollen.",
  },
  strandraeuber: {
    id: "strandraeuber",
    title: "Strandräuber",
    emoji: "🦹",
    color: "#e11d48",
    tagline: "Einer hält am Ende den Strandräuber — und verliert.",
    goal: "Alle Paare ablegen und bloß nicht als Letzter mit dem Strandräuber dastehen!",
    rules: [
      "37 Karten werden gleichmäßig ausgeteilt (18 Paare + 1 Strandräuber).",
      "Sofort alle Paare aus der Starthand offen ablegen.",
      "Reihum: eine verdeckte Karte vom Vorspieler ziehen.",
      "Entsteht ein Paar? Sofort ablegen!",
      "Spieler ohne Karten scheiden erfolgreich aus.",
      "Wer am Ende als Einziger noch Karten hält, hat den Strandräuber — und verliert.",
    ],
    proTip: "Mische deine Karten, bevor der nächste Spieler zieht — so kann niemand den Strandräuber anhand seiner Position erkennen.",
  },
  mahjong: {
    id: "mahjong",
    title: "GezeitenSteine",
    emoji: "🀄",
    color: "#D4A820",
    tagline: "Wenn die Gezeiten sich zurueckziehen, werden die Steine frei.",
    goal: "Entferne alle Steine vom Spielfeld, indem du passende freie Paare anklickst.",
    rules: [
      "Ein Stein ist 'frei', wenn er seitlich (links oder rechts) nicht blockiert ist UND kein anderer Stein auf ihm liegt.",
      "Tippe zwei identische freie Steine an — sie werden als Paar entfernt.",
      "Ausnahme Jahreszeiten: Fruhling, Sommer, Herbst und Winter passen jeweils zu allen anderen Jahreszeiten.",
      "Ausnahme Blumen: Hibiskus, Seeanemone, Seerose und Stranddistel passen zu allen anderen Blumen.",
      "Denke voraus! Einen Stapel von oben abtragen oeffnet neue Moeglichkeiten.",
      "Halte das Spielfeld im Gleichgewicht — raeume nicht nur eine Seite ab.",
      "Hinweis-Button zeigt ein mogliches Paar. Mischung verteilt verbleibende Steine neu.",
      "Pinch-Geste oder Scroll-Rad zum Zoomen — unverzichtbar bei kleinen Displays.",
    ],
    proTip: "Siehst du drei gleiche freie Steine? Entferne zuerst den, der die meisten anderen Steine blockiert — der dritte bleibt frei fuer spaeter.",
  },
  strandoku: {
    id: "strandoku",
    title: "Strandoku",
    emoji: "🔢",
    color: "#38bdf8",
    tagline: "Das meistgespielte Logikrätsel der Welt — jetzt am Strand.",
    goal: "Fülle das Raster so, dass jede Zahl in jeder Zeile, Spalte und jedem Block genau einmal vorkommt.",
    rules: [
      "Classic (9×9): Zahlen 1–9 dürfen in jeder Zeile, Spalte und jedem 3×3-Block nur einmal vorkommen.",
      "Mega (12×12 / 16×16): Größere Raster mit Zahlen 1–12 bzw. 1–16 — für erfahrene Rätsler.",
      "Irregular: Statt quadratischer Blöcke werden unregelmäßige Bereiche verwendet.",
      "Diagonal: Zusätzlich zur Grundregel darf jede Zahl auch auf den beiden Hauptdiagonalen nur einmal vorkommen.",
      "Samurai: Fünf überlappende 9×9-Gitter — das absolute Meisterstück.",
      "Killer: Felder sind in Käfige gruppiert — die Summe der Zahlen im Käfig muss stimmen, Wiederholungen verboten.",
      "Notizen: Tippe lange auf eine Zelle, um Kandidaten-Nummern einzutragen — ohne eine endgültige Zahl zu setzen.",
    ],
    proTip: "Beginne immer bei der Zelle mit den meisten Einschränkungen. Kandidaten-Notizen sind dein bester Freund bei Schwer und Experte.",
  },
  wellensumme: {
    id: "wellensumme",
    title: "WellenSumme",
    emoji: "➕",
    color: "#c084fc",
    tagline: "Das Kreuzworträtsel mit Zahlen statt Buchstaben.",
    goal: "Fülle alle leeren Felder mit Ziffern 1–9, sodass jeder Block die vorgegebene Summe ergibt — ohne Wiederholung im Block.",
    rules: [
      "Schwarze Felder mit Schrägstrich trennen die Blöcke: die Zahl oben rechts ist die Summe senkrecht, unten links waagerecht.",
      "Innerhalb eines Blocks darf jede Ziffer 1–9 nur einmal vorkommen.",
      "Alle weißen Felder müssen ausgefüllt werden — es gibt keine leeren Felder.",
      "Es gibt immer genau eine Lösung, die durch logisches Schlussfolgern gefunden werden kann.",
      "Notizen: Tippe auf eine Zelle und wechsle in den Notiz-Modus, um mögliche Ziffern einzutragen.",
    ],
    proTip: "Wenn ein Zweier-Block die Summe 3 ergeben muss, können es nur 1 und 2 sein. Solche 'Pflicht-Kombinationen' sind der Schlüssel zum Erfolg.",
  },
  kuestenkrieg: {
    id: "kuestenkrieg",
    title: "Küstenkrieg",
    emoji: "⚓",
    color: "#fb7185",
    tagline: "Logisches Solo-Rätsel und klassisches 2-Spieler-Seegefecht.",
    goal: "Solo: Erschließe per Logik, wo die Schiffe versteckt sind. 2-Spieler: Versenke alle Schiffe des Gegners.",
    rules: [
      "Solo-Rätsel: Zahlen am Rand zeigen, wie viele Schiffsfelder in dieser Zeile bzw. Spalte liegen.",
      "Solo: Schiffe liegen nur waagerecht oder senkrecht — sie berühren sich nicht, auch nicht diagonal.",
      "Solo: Manchmal sind einzelne Schiffsteile oder Wasserfelder als Starthilfe bereits eingetragen.",
      "2-Spieler: Platziere deine Flotte heimlich auf deinem Raster — dann greift ihr abwechselnd an.",
      "2-Spieler: Ein Feld anvisieren — 'Treffer!', 'Verfehlt!' oder 'Versenkt!' als Antwort.",
      "2-Spieler: Wer zuerst alle gegnerischen Schiffe versenkt, gewinnt das Seegefecht.",
      "Gegen KI spielbar — Matrose (zufällig), Kapitän (wahrscheinlichkeitsbasiert), Admiral (hunting/targeting).",
    ],
    proTip: "Solo-Tipp: Wenn eine Zeile die Randzahl 0 hat, ist die gesamte Zeile Wasser. Fang dort an — das gibt sofort viele Informationen.",
  },
  duenenschatten: {
    id: "duenenschatten",
    title: "DünenSchatten",
    emoji: "◼",
    color: "#fbbf24",
    tagline: "Das japanische Zahlen-Ausschluss-Rätsel.",
    goal: "Schwärze Felder so ein, dass keine Zahl doppelt in einer Zeile/Spalte vorkommt, geschwärzte Felder sich nicht berühren und alle weißen Felder verbunden bleiben.",
    rules: [
      "Tippe ein Feld an, um es schwarz einzufärben. Erneutes Tippen macht es wieder weiß.",
      "Kein Zahlenwert darf in derselben Zeile oder Spalte mehr als einmal bei weißen Feldern erscheinen.",
      "Zwei geschwärzte Felder dürfen sich horizontal oder vertikal nicht direkt berühren.",
      "Alle nicht geschwärzten Felder müssen am Ende einen einzigen zusammenhängenden Bereich bilden.",
      "Markierung: Tippe lange auf ein Feld, um es mit einem Kreis als 'sicher weiß' zu markieren.",
    ],
    proTip: "Wenn eine Zahl dreimal in einer Reihe vorkommt: das mittlere Feld muss immer weiß bleiben — die äußeren Felder können geschwärzt werden.",
  },
  inselbruecke: {
    id: "inselbruecke",
    title: "Inselbrücke",
    emoji: "🌉",
    color: "#4ade80",
    tagline: "Das japanische Brücken-Verbindungs-Rätsel.",
    goal: "Verbinde alle Inseln mit Brücken, sodass jede Insel genau so viele Brücken hat wie ihre Zahl angibt — und alle Inseln miteinander verbunden sind.",
    rules: [
      "Tippe zwischen zwei benachbarten Inseln, um eine Brücke zu ziehen. Erneutes Tippen legt eine zweite Brücke.",
      "Brücken verlaufen nur waagerecht oder senkrecht — niemals diagonal.",
      "Maximal 2 Brücken dürfen in dieselbe Richtung zwischen zwei Inseln verlaufen.",
      "Brücken dürfen keine anderen Inseln oder bestehenden Brücken kreuzen.",
      "Die Zahl einer Insel gibt an, wie viele Brücken insgesamt von ihr abgehen müssen (Summe aller Richtungen).",
      "Am Ende müssen alle Inseln über Brückenwege miteinander verbunden sein.",
    ],
    proTip: "Eine Eckinsel mit der Zahl 4 muss in beide Richtungen je 2 Brücken haben — sofort platzierbar. Beginne immer mit solchen 'eindeutigen' Inseln.",
  },
  wortwelle: {
    id: "wortwelle",
    title: "WortWelle",
    emoji: "🌊",
    color: "#06b6d4",
    tagline: "Das Wordle-Rätsel auf Deutsch — mit Umlauten, Hard Mode und Tageswort.",
    goal: "Errate das versteckte deutsche Wort in so wenigen Versuchen wie möglich.",
    rules: [
      "Gib ein gültiges deutsches Wort ein und bestätige mit ↵ (Enter).",
      "🟩 Grün: Dieser Buchstabe ist im Wort und steht an der richtigen Stelle.",
      "🟨 Gelb: Dieser Buchstabe ist im Wort, steht aber an der falschen Stelle.",
      "⬛ Grau: Dieser Buchstabe kommt im gesuchten Wort nicht vor.",
      "Die Farben auf der Tastatur zeigen deinen besten bekannten Status je Buchstabe.",
      "Doppelbuchstaben werden korrekt behandelt: zwei gleiche Buchstaben im Rateversuch werden nur so oft gelb/grün markiert, wie der Buchstabe tatsächlich vorkommt.",
      "Hard Mode (Experte): Einmal bestätigte grüne Buchstaben müssen in allen Folgeversuchen an derselben Stelle stehen. Gelbe Buchstaben müssen weiterhin verwendet werden.",
      "Leicht = 4 Buchstaben / 7 Versuche · Mittel = 5 / 6 · Schwer = 5 / 5 · Experte = 6 / 5 + Hard Mode.",
      "Das 'Wort des Tages' ist täglich dasselbe für alle Spieler — vergleiche dein Ergebnis!",
    ],
    proTip: "Starte mit Wörtern, die viele häufige Vokale und Konsonanten enthalten — z.B. STEIN oder ABEND. So deckst du in den ersten zwei Versuchen die meisten Möglichkeiten ab.",
  },
  meermau: {
    id: "meermau",
    title: "MeerMau",
    emoji: "🂠",
    color: "#7c3aed",
    tagline: "Wer zuletzt noch Karten hält, zahlt die Zeche.",
    goal: "Als Erster alle Handkarten ablegen und \"MAU!\" rufen.",
    rules: [
      "Jeder Spieler erhält 5 Karten. Die oberste Karte des Stapels startet die Ablage.",
      "Lege eine Karte ab, die entweder dieselbe Farbe oder denselben Wert hat.",
      "7 = nächster Spieler muss 2 Karten ziehen (stapelbar!).",
      "8 = nächster Spieler wird übersprungen.",
      "Bube (J) = Farbwunsch – du bestimmst, welche Farbe als nächstes gespielt werden muss.",
      "Hast du nur noch eine Karte, musst du \"MAU!\" sagen – sonst Strafkarten!",
      "Wer alle Karten losgeworden ist, gewinnt die Runde. Die übrigen Spieler erhalten Strafpunkte.",
      "Bei 100 Punkten scheidet ein Spieler aus. Letzter Überlebender gewinnt das Spiel!",
    ],
    proTip: "Den Buben (J) aufheben für kritische Momente. Nichts ist befriedigender, als im richtigen Moment die Farbe zu wechseln.",
  },
  sonnenrad: {
    id: "sonnenrad",
    title: "Sonnenrad",
    emoji: "☀️",
    color: "#D4A820",
    tagline: "Einmal täglich volle Power — ansonsten immer spielbar mit 1/3 Punkte.",
    goal: "Drehe drei Muschelkarten auf, erreiche eine Leiterstufe und klettere so hoch wie du dich traust.",
    rules: [
      "Tippe auf die Karten — drei Muschelkarten werden gemischt und aufgedeckt.",
      "3 gleiche Basissymbole (Sonne, Welle, Palme, Muschel) = Stufe 2 auf der Bonusleiter.",
      "2 gleiche Symbole = Stufe 1. Kein Treffer = Runde endet sofort.",
      "3 Sonnenschirme = direkter Jackpot auf Stufe 4.",
      "Auf der Leiter: 'Einsammeln' sichert deine Punkte. 'Klettern' startet die Timing-Herausforderung.",
      "Beim Klettern wechselt ein Marker zwischen deiner Stufe und der nächsten (alle 175ms).",
      "'Jetzt!' im Zielfeld treffen = eine Stufe weiter. Verfehlen = Runde endet, bisherige Stufe zählt.",
      "Tagesbonus (einmal täglich): volle Punkte bis zu 600. Normalspiel: 1/3 der Punkte.",
    ],
    proTip: "Klettere nicht zu gierig. Der Unterschied zwischen Stufe 4 (275 Pkt.) und Stufe 5 (400 Pkt.) klingt verlockend — aber Verfehlen bringt dich zurück auf Stufe 4. Einsammeln ist oft die klügere Wahl.",
  },
  perlentaucher: {
    id: "perlentaucher",
    title: "Perlentaucher",
    emoji: "🤿",
    color: "#0EA5E9",
    tagline: "Match-3 am Meeresgrund — tausche Schätze aus, bilde Reihen und knacke 150 Level.",
    goal: "Erreiche die Zielpunktzahl, bevor dir die Züge ausgehen.",
    rules: [
      "Das Spielfeld ist ein 8×8-Gitter mit 6 Schatztypen: Perle, Seeglas, Muschel, Seestern, Koralle und Seetang.",
      "Tippe auf ein Feld und dann auf ein benachbartes, um die beiden Schätze zu tauschen.",
      "Drei oder mehr gleiche Schätze in einer Reihe oder Spalte werden entfernt und bringen Punkte.",
      "Kettenreaktionen entstehen automatisch, wenn fallende Schätze neue Reihen bilden — sie bringen Bonuspunkte.",
      "Spezialschätze entstehen bei längeren Reihen: Gestreift (5 in einer Reihe) löscht eine ganze Zeile oder Spalte.",
      "Eingepackt (L- oder T-Form) löscht ein 3×3-Feld. Perlenkette (6+ oder Kreuz) löscht alle Schätze desselben Typs.",
      "Zwei Spezialschätze kombiniert ergeben mächtige Kombo-Effekte.",
      "Jedes Level hat ein Zug-Limit und eine Zielpunktzahl. Das Spiel endet, wenn das Ziel erreicht oder die Züge aufgebraucht sind.",
      "Bei einem Deadlock (keine gültige Bewegung mehr) wird das Brett automatisch neu gemischt.",
    ],
    proTip: "Suche zuerst nach Zügen, die Spezialschätze erzeugen. Eine Perlenkette, die einen gestreiften Schatz trifft, räumt das halbe Brett ab und kann ein Level im Alleingang entscheiden.",
  },
};
